name: Tests

on:
    push:
        branches: [ ga-test ]
    pull_request:
        branches: [ ga-test ]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Install system dependencies
                run: echo 'It works!'
